name: Build, JaCoCo, Allure, and Deploy Reports
on:
  pull_request:
    branches:
      - development
      - staging
jobs:
  build-test-reports:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download external pom.xml
        run: |
          curl -o external-pom.xml https://raw.githubusercontent.com/AmaliTech-Training-Academy/talentradar-qa-rw/refs/heads/report-coverage/external-pom.xml

      - name: Download allure.properties into resources
        run: |
          mkdir -p src/test/resources
          curl -o src/test/resources/allure.properties https://raw.githubusercontent.com/AmaliTech-Training-Academy/talentradar-qa-rw/refs/heads/report-coverage/allure.properties

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run tests and generate reports
        run: mvn clean verify -f external-pom.xml
        continue-on-error: true

      - name: Upload coverage badge
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: target/site/jacoco/jacoco.xml

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure
          path: target/allure-results/
          retention-days: 1

      - name: Upload JaCoCo results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jacoco
          path: target/site/jacoco/
          retention-days: 1

  deploy-reports:
    runs-on: ubuntu-latest
    needs: build-test-reports
    if: always()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Allure results
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: allure
          path: allure-results/

      - name: Get published reports history
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Download report dashboard HTML into publish
        run: |
          mkdir -p gh-pages-deploy
          mkdir -p gh-pages-deploy/jacoco
          mkdir -p gh-pages-deploy/allure
          curl -o gh-pages-deploy/index.html https://raw.githubusercontent.com/AmaliTech-Training-Academy/talentradar-qa-rw/refs/heads/report-coverage/reports-index.html

      - name: Inject repo name and build date (UTC+2) into reports dashboard HTML
        run: |
          REPO_NAME=$(basename "$GITHUB_REPOSITORY")
          DATE=$(TZ="Etc/GMT-2" date +"%Y-%m-%d %H:%M UTC+2")
          sed -i "s|{{REPO_NAME}}|$REPO_NAME|g" gh-pages-deploy/index.html
          sed -i "s|{{BUILD_DATE}}|$DATE|g" gh-pages-deploy/index.html
      
      - name: Download JaCoCo results
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: jacoco
          path: gh-pages-deploy/jacoco/

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          gh-pages: gh-pages/allure
          subfolder: allure
          allure_report: gh-pages-deploy/allure
          keep_reports: 5

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: gh-pages-deploy
          force_orphan: true
